# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class UI_NeuralNetwork(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.scene = QtWidgets.QGraphicsScene()
        self.setupUi(self)
        self.show()

    def setupUi(self, NeuralNetwork):
        NeuralNetwork.setObjectName("NeuralNetwork")
        NeuralNetwork.resize(960, 540)
        self.graphicsView = QtWidgets.QGraphicsView(NeuralNetwork)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 601, 601))
        self.graphicsView.setObjectName("graphicsView")
        self.formLayoutWidget = QtWidgets.QWidget(NeuralNetwork)
        self.formLayoutWidget.setGeometry(QtCore.QRect(620, 20, 296, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_neurons = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_neurons.setObjectName("label_neurons")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_neurons)
        self.nb_neurons = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.nb_neurons.setMinimum(50)
        self.nb_neurons.setMaximum(2000)
        self.nb_neurons.setProperty("value", 200)
        self.nb_neurons.setObjectName("nb_neurons")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nb_neurons)
        self.label_gamma = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_gamma.setObjectName("label_gamma")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_gamma)
        self.gamma = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.gamma.setDecimals(2)
        self.gamma.setMinimum(0.5)
        self.gamma.setMaximum(1.0)
        self.gamma.setSingleStep(0.05)
        self.gamma.setProperty("value", 0.9)
        self.gamma.setObjectName("gamma")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gamma)
        self.label_beta = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_beta.setObjectName("label_beta")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_beta)
        self.beta = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.beta.setDecimals(2)
        self.beta.setMinimum(0.1)
        self.beta.setMaximum(0.6)
        self.beta.setSingleStep(0.05)
        self.beta.setObjectName("beta")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.beta)
        self.label_alcohol_concentration = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_alcohol_concentration.setObjectName("label_alcohol_concentration")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_alcohol_concentration)
        self.alco_concen = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.alco_concen.setDecimals(2)
        self.alco_concen.setMinimum(-1.0)
        self.alco_concen.setMaximum(1.0)
        self.alco_concen.setSingleStep(0.05)
        self.alco_concen.setProperty("value", 0.5)
        self.alco_concen.setObjectName("alco_concen")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.alco_concen)
        self.label_dist = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_dist.setObjectName("label_dist")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_dist)
        self.dist = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.dist.setDecimals(0)
        self.dist.setMinimum(50.0)
        self.dist.setMaximum(300.0)
        self.dist.setSingleStep(10.0)
        self.dist.setProperty("value", 50.0)
        self.dist.setObjectName("dist")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dist)
        self.label_deltaT = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_deltaT.setObjectName("label_deltaT")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_deltaT)
        self.deltaT = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.deltaT.setDecimals(2)
        self.deltaT.setMinimum(0.05)
        self.deltaT.setMaximum(0.3)
        self.deltaT.setSingleStep(0.05)
        self.deltaT.setObjectName("deltaT")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.deltaT)
        self.formLayoutWidget_2 = QtWidgets.QWidget(NeuralNetwork)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(620, 220, 276, 83))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.poids = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.poids.setObjectName("poids")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.poids)
        self.psycho = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.psycho.setObjectName("psycho")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.psycho)
        self.decrease_poten = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.decrease_poten.setObjectName("decrease_poten")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.decrease_poten)
        self.start = QtWidgets.QPushButton(NeuralNetwork)
        self.start.setGeometry(QtCore.QRect(650, 390, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.pause = QtWidgets.QPushButton(NeuralNetwork)
        self.pause.setGeometry(QtCore.QRect(770, 390, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pause.setFont(font)
        self.pause.setObjectName("pause")
        self.gridLayoutWidget = QtWidgets.QWidget(NeuralNetwork)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(620, 310, 247, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nbActive = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.nbActive.setChecked(False)
        self.nbActive.setObjectName("nbActive")
        self.gridLayout.addWidget(self.nbActive, 2, 0, 1, 1)
        self.networkMap = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.networkMap.setAutoFillBackground(True)
        self.networkMap.setChecked(True)
        self.networkMap.setObjectName("networkMap")
        self.gridLayout.addWidget(self.networkMap, 1, 0, 1, 1)

        self.retranslateUi(NeuralNetwork)
        QtCore.QMetaObject.connectSlotsByName(NeuralNetwork)

    def retranslateUi(self, NeuralNetwork):
        _translate = QtCore.QCoreApplication.translate
        NeuralNetwork.setWindowTitle(_translate("NeuralNetwork", "Neural Network Dialog"))
        self.label_neurons.setText(_translate("NeuralNetwork", "Number of neurons"))
        self.label_gamma.setText(_translate("NeuralNetwork", "Preserve Coef"))
        self.label_beta.setText(_translate("NeuralNetwork", "Transmission Loss"))
        self.label_alcohol_concentration.setText(_translate("NeuralNetwork", "Alcohol Concetration"))
        self.label_dist.setText(_translate("NeuralNetwork", "Neurons Distance"))
        self.label_deltaT.setText(_translate("NeuralNetwork", "Timestep (ms)"))
        self.poids.setText(_translate("NeuralNetwork", "Transmission with weights "))
        self.psycho.setText(_translate("NeuralNetwork", "Affected by psychoactive subtances"))
        self.decrease_poten.setText(_translate("NeuralNetwork", "With potential decrease"))
        self.start.setText(_translate("NeuralNetwork", "START"))
        self.pause.setText(_translate("NeuralNetwork", "PAUSE"))
        self.nbActive.setText(_translate("NeuralNetwork", "Number of active neurons / time"))
        self.networkMap.setText(_translate("NeuralNetwork", "Network map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NeuralNetwork = QtWidgets.QDialog()
    ui = UI_NeuralNetwork()
    ui.setupUi(NeuralNetwork)
    # NeuralNetwork.show()
    sys.exit(app.exec_())
